format_version = 2

[apps.MetaversalDemo]
identifier = 'foundation.wabi.MetaversalDemo'
product = 'MetaversalDemo'
version = '1.0.0'
category = 'public.app-category.graphics-design'

[apps.MetaversalDemo.plist]
commit = '$(COMMIT_HASH)'